name: ui
description: "Rehan Apple Style Music Player"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  on_audio_query: ^2.9.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.13
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
